### ISSUE TITLE
RSCP

### ISSUE THREAD

**Issue by git-kick** [jnk-cons/easy-rscp#1]
ad [DERATE_AT_PERCENT_VALUE](https://jnk-cons.github.io/easy-rscp/kdoc/easy-rscp/de.jnkconsulting.e3dc.easyrscp.api.frame.tags/-e-m-s-tag/-d-e-r-a-t-e_-a-t_-p-e-r-c-e-n-t_-v-a-l-u-e/index.html)

Empirische Erkenntnis:
Das ist das Verältnis max. Einspeiseleistung / INSTALLED_PEAK_POWER in Prozent.

Beispiel: Die Anlage hat 7,7 kWp und darf nur 70% dieser Peakleistung einspeisen.
INSTALLED_PEAK_POWER = 7700 [W]
DERATE_AT_PERCENT_VALUE = 70 [%]
7700 * 70 / 100 = 5390
Die Anlage wird bei 5.390 W Einspeisung abgeregelt.
Den Wert DERATE_AT_PERCENT_VALUE kann nur der Installateur ändern.

**Comment by jnk-cons** [comment]
Besten Dank.

Ich habe die Dokumentation aufgenommen. Auch die Idee mit dem Links finde ich gut. In der API befindet sich nun ein create ticket link über jedem Tag, der bereits ein paar Werte vorbelegen sollte.
